layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Kotlin
    web_url: https://kotlinlang.org/
    image_url: https://raw.githubusercontent.com/oddlyspaced/oddlyspaced.github.io/master/assets/logo_kotlin.png

  - name: Android App Development
    web_url: https://developer.android.com/
    image_url: https://raw.githubusercontent.com/oddlyspaced/oddlyspaced.github.io/master/assets/logo_android.png

  - name: Flutter
    web_url: https://flutter.dev/
    image_url: https://raw.githubusercontent.com/oddlyspaced/oddlyspaced.github.io/master/assets/logo_flutter.png
  
  - name: Linux
    web_url: https://linux.org
    image_url: https://raw.githubusercontent.com/oddlyspaced/oddlyspaced.github.io/master/assets/logo_linux.png

  - name: C Programming
    web_url: https://en.wikipedia.org/wiki/C_(programming_language)
    image_url: https://raw.githubusercontent.com/oddlyspaced/oddlyspaced.github.io/master/assets/logo_c.png

  - name: Python
    web_url: https://www.python.org/
    image_url: https://raw.githubusercontent.com/oddlyspaced/oddlyspaced.github.io/master/assets/logo_python.png
